### ISSUE TITLE
July 10th, 2018 Meeting - Steve Albers

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#1]
Date: July 10th, 2018
Speaker: Steve Albers
Sponsor: Swift Kick
https://www.meetup.com/Hampton-Roads-NET-Users-Group/events/248779569/

**Comment by SteveAlbers** [comment]
Date: July 10th, 2018
Speaker: Steve Albers
Sponsor: [TODO]
Title: Progressive Web Apps Today
Description:  Progressive Web Apps can help you build better, more reliable apps today!  In this talk we explain what PWAs are, add PWA support to a web site, and look at the benefits and challenges of building a Progressive Web App today.
Bio:  Steve Albers is a software developer and technology fan focused on web technology, system integration and performance. By day he is a Senior Innovator at Cleverspeck.
