### ISSUE TITLE
April 9th, 2019 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#11]
Date: April 9th, 2019 
Speaker: Kendall Miller (@kendallmiller)
Sponsor: Loupe https://onloupe.com (@kendallmiller )

**Comment by 1kevgriff** [comment]
Fantastic!  You're in @kendallmiller

**Comment by kendallmiller** [comment]
We (Loupe) can also sponsor that week as well.

**Comment by 1kevgriff** [comment]
Done!

**Comment by 1kevgriff** [comment]
@kendallmiller Still good to go?

**Comment by kendallmiller** [comment]
Yep, need to remember to book a hotel :)
