### ISSUE TITLE
June 11th, 2019 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#13]
Date: June 11th, 2019
Speaker: Sidney Andrews (@seesharprun)
Sponsor:  Progress (@sfaatz)

**Comment by sfaatz** [comment]
Progress would like to sponsor.

**Comment by 1kevgriff** [comment]
Thank you!!

**Comment by seesharprun** [comment]
I'm interested in speaking.

**Comment by 1kevgriff** [comment]
@seesharprun excellent!

**Comment by seesharprun** [comment]
Potential title and description:

Introducing Azure DevOps!

DevOps is about people, process, and products. Getting it all right requires effort, but the benefits to your organization and customers can be huge. Microsoft has a fantastic set of products that can help you get the most out of the cloud with any language on any platform. In this demo-heavy talk, Sidney will show you how to use the new Azure DevOps tooling to automate builds and releases in your organization. The session will specifically focus on the new YAML build pipeline, building Release pipelines, integrating Azure Pipelines with GitHub and the Azure Repos service.

**Comment by seesharprun** [comment]
Here's a more advanced topic option:

**Docker, .NET Core, and Azure DevOps; Oh My!**

Building .NET Core applications automatically require effort, but the benefits to your organization and customers can be huge. Azure DevOps has a set of tools that make it easier to build .NET Core applications and eventually Dockerize them. In this demo-heavy talk, Sidney will show you how to use the new Azure DevOps tooling to automate builds and releases of .NET Core applications in your organization. The session will specifically focus on the new YAML build pipeline, building Release pipelines, integrating Azure Pipelines with GitHub repositories and creating GitHub releases automatically. Building on top of that, Sidney will then show you how to use Docker in every stage of your CI and CD processes. The session will feature demos on using a Docker container image for your build agents, building Docker images in Azure Pipelines and pushing new container images to Docker Hub automatically.

**Comment by seesharprun** [comment]
> I'm thinking out loud here...

What's the capability for an interactive session. I have a system where I can distribute Azure subscriptions to attendees (not Azure Passes) and they can use the Cloud Shell (or a VM) to build their .NET Core applications in Docker.

I don't know if having a hands-on component will bring value-add to your user group.

I also wonder if WiFi will be available for everyone.
