### ISSUE TITLE
August 13th, 2019 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#15]
Date: August 13th, 2019
Speaker: Linda Nichols @lynnaloo
Sponsor: [ TODO ]

**Comment by lynnaloo** [comment]
I can do a Logic Apps full hour talk or lightning talk.

**Comment by 1kevgriff** [comment]
SOLD

**Comment by drew-carpenter** [comment]
@lynnaloo can you provide a description for your talk.

**Comment by lynnaloo** [comment]
Serverless Integrations with Logic Apps

Logic Apps is part of the Serverless toolset on Microsoft Azure and is a powerful automation and workflow tool. However, one of its amazing and understated strengths is as an integration tool. It can be used with smaller and enterprise applications to connect internal and external APIs, Serverless Applications, business applications, and even on-premises systems. It also has over 300 built-in "connectors" that allow it to be a low-code and no-code solution for developers.

In this talk, I'll be digging a little deeper into Logic Apps as the bridge between the parts of your application and demonstrating some interesting (and fun) use-cases for Logic Apps, including a hybrid system.

**Comment by drew-carpenter** [comment]
Issuetrak is sponsoring
