### ISSUE TITLE
September 10th, 2019 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#16]
Date: September 10th, 2019
Speaker: Kevin Jones (@vcsjones)
Sponsor: Marathon Consulting (@TMarsdenMarathon)

**Comment by TMarsdenMarathon** [comment]
Put Marathon down as a sponsor for this one.

**Comment by 1kevgriff** [comment]
done!  thanks!

**Comment by vcsjones** [comment]
I can take speaker for this one; topic TBD.

**Comment by 1kevgriff** [comment]
@vcsjones Thank you, sir!

**Comment by Blue-speed** [comment]
@vcsjones can you provide an abstract for your talk?

**Comment by vcsjones** [comment]
*Title*: "C# 8 Nullable Reference Types - What Are They?"

*Abstract*:
C# 8 introduces a new feature called Nullable Reference Types. What are they, and how we can use them to be better C# developers by reducing bugs and making code easier to understand?

In this session we'll discuss what Nullable Reference Types are, how to use them and adopt them effectively. We'll take what we have learned and apply them to a real OSS code base.
