### ISSUE TITLE
November 12th, 2019 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#18]
Date: November 12th, 2019
Speaker: Drew C @Blue-speed 
Sponsor: TECHEAD (@AHSNEAD)

**Comment by AHSNEAD** [comment]
TECHEAD would be glad sponsor this event.

**Comment by 1kevgriff** [comment]
@AHSNEAD You got it!  Thanks!

**Comment by joelhulen** [comment]
I cannot commit because I may be out of town that week. I'll know for sure by the end of the week. If I am in town and no one else has stepped up, I'll submit a session.

**Comment by Blue-speed** [comment]
I will be talking about Linqpad.
