### ISSUE TITLE
December 10th, 2019 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#19]
Date: December 10th, 2019
Speaker: Sidney Andrews (@seesharprun)
Sponsor: Vaco

**Comment by 1kevgriff** [comment]
Confirmed Vaco as sponsor.

**Comment by seesharprun** [comment]
I’m interested in speaking!

**Comment by 1kevgriff** [comment]
SOLD!  Give us some options?  We'll start promoting asap

**Comment by seesharprun** [comment]
What about Visual Studio Online? I’m digging into it deeply as part of a pilot to use it with Chromebook-restricted classrooms

**Comment by seesharprun** [comment]
Other potential topic: Microsoft’s new Identity Platform and how you can use it to integrate with AAD or Microsoft Accounts in a few lines of code. I can even throw in some Graph queries and traversal.

Just pick a topic and I will put together a title and abstract

**Comment by 1kevgriff** [comment]
@seesharprun Identity sounds great and more applicable to members.

**Comment by seesharprun** [comment]
I contributed some of the Graph Auth SDK code so I will put together a talk around MSAL, Microsoft Identity platform and the Graph
