### ISSUE TITLE
August 2018 Meeting - Derik Whittaker

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#2]
Date: August 14, 2018
Speaker: Derik Whittaker
Sponsor: Marathon (thanks @TMarsdenMarathon!)
https://www.meetup.com/Hampton-Roads-NET-Users-Group/events/251695779/

Title: `Cultivating your Infrastructure with Terraform`
Abstract: 
>We no longer live in a world where Infrastructure Engineers are required to spin up new environments. In the world of Cloud Environments, Serverless platforms and containers developers are more and more often expected to spin up and maintain their infrastructure.

>In this brave new world it is important to be able to script out the building of this infrastructure. This is where Terraform comes in. Terraform is a platform for building and maintaining your cloud environments in a convenient and reliable way.

**Comment by jamessdixon** [comment]
Can we get someone more creditable?

**Comment by TMarsdenMarathon** [comment]
Marathon can sponsor this one.

**Comment by 1kevgriff** [comment]
BIO: Derik Whittaker is a Bit Pusher who specializes in all things .Net and dabbles in the world of Node and Javascript. Derik has been building enterprise systems, mostly on top of the .Net technology stack for over 19 years. Along the way has picked up a thing or two about how to create enterprise scale software systems. During his 19 year career Derik has worked in many different industries ranging from Mortgage, Marking, Healthcare, Retail, Insurance, Automotive and Online Entertainment. Currently Derik is senior engineer working for Quicken Loans, the countries largest commercial mortgage company. Derik believes that the job of a developer is more than just turning syntax into working 1s and 0s. He believes that our job is to produce a system which gets out of the users way and allows them to do their job better. Derik was previously awarded the Microsoft MVP in C# 7 times. He is also a member of the ASPInsiders group. Derik is also a Pluralsight Author with 4 courses under his belt. He is a community leader, helping to organize events such as Chicago Codeapalooza, Chicago Code Camp and the Raleigh Code Camp. Outside of his day job you can find Derik hanging out with his beautiful wife Tiffany and his 2 awesome boys Brendan and Ryan (normally on a soccer pitch).

**Comment by 1kevgriff** [comment]
@Blue-speed We have the abstract and bio from Derik.  Let's schedule and promote early!
