### ISSUE TITLE
 January 14th, 2020 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#21]
Date: January 14th, 2020
Speaker: Jenna Charlton (@jcharlton77)
Sponsor: APEX Systems (smenees@apexsystems.com - Shannon Menees)

Talk via Zoom link.

**Comment by 1kevgriff** [comment]
APEX agreed to sponsor Jan.

**Comment by jcharlton777** [comment]
Jenna Charlton 
Testing 101 for Devs

**Comment by 1kevgriff** [comment]
Thanks @jcharlton777!!

**Comment by Blue-speed** [comment]
@jcharlton77 can you give us a brief synopsis of your talk?

**Comment by jcharlton777** [comment]
I'm so sorry this fell off my radar. Here's the abstract :)

In Agile, quality has become a team responsibility. Increasingly developers and non-testers are being asked to test and ""shift left"" but are rarely given the tools to ensure their testing is up to snuff. This often results in wasted time and effort and costly bugs. In this session, we’ll cover some of the basics of exploratory testing, testing terminology, and start to think like testers.

Takeaways
• Session based testing with charters
• Testing vocabulary and techniques
• Testing lifecycle
• Understanding and communicating risk
• Why automation isn’t always the answer

**Comment by 1kevgriff** [comment]
Join me at January 2020: Jenna Charlton: Testing 101 for Devs

 http://meetu.ps/e/HxTBL/1MKqv/a
