### ISSUE TITLE
February 11, 2020 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#22]
Meeting Date: February 11, 2020  
Speaker: Joel Hulen (@joelhulen)
Sponsor: [ TODO ]

**Comment by joelhulen** [comment]
I'm interested in speaking. I'll do an Azure-focused talk about real-time stream processing.

If no one steps up to sponsor prior to then, I may do that as well.

**Comment by 1kevgriff** [comment]
@joelhulen SOLD

**Comment by 1kevgriff** [comment]
@joelhulen You still up for sponsoring as well?

**Comment by joelhulen** [comment]
If no one else steps up, sure.

**Comment by 1kevgriff** [comment]
@joelhulen No other takers - so we'd love it if you'd cover food/drinks.
