### ISSUE TITLE
March 10, 2020 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#23]
Meeting Date: March 10, 2020  
Speaker: Brady Gaster (@bradygaster)
Sponsor: [ TODO ]

**Comment by bradygaster** [comment]
I can do this one.

**Comment by 1kevgriff** [comment]
@bradygaster You're the man!  We'll do the talk over zoom

**Comment by bradygaster** [comment]
@1kevgriff what time of day will this be? or, send me an invite. :)

**Comment by 1kevgriff** [comment]
@bradygaster 6:30pm ET, so 3:30p your time?  

We can create the meetup invite now so it's on your calendar.

**Comment by bradygaster** [comment]
I presume you have my email addy. jic it's first name last-name-initial at you know where dot com.

**Comment by 1kevgriff** [comment]
@bradygaster Know what you want to speak on?  Anything juicy that hasn't been released?

**Comment by bradygaster** [comment]
@1kevgriff well I wouldn't be able to disclose something secret in this forum, now would I....?

**Comment by Blue-speed** [comment]
@bradygaster can you provide a bio and short synopses of your talk? Thanks.

**Comment by bradygaster** [comment]
So sorry for the lag, folks! Here you are: 

Bio
Brady Gaster is a senior program manager in the ASP.NET team at Microsoft, where he works on SignalR, microservices and APIs, and integration with Azure service teams in hopes to make it exciting for developers who work on .NET apps to party in the cloud. You can find Brady on Twitter at @bradygaster when he's not learning with (or from) his 2 sons, tinkering with code, or making music in his basement using various synthesizers and guitars. 

Session
You may know a bit about SignalR from its upbringing as the real-time framework for .NET. While still true in that SignalR for .NET Core is a thing now, SignalR has evolved and is no longer “just for .NET developers.” With the new Azure SignalR Service providing a common back-end for any real-time app needs you have, you can use the various client SDKs now available for SignalR – JavaScript and Java, to name a few – without any .NET Code. In addition, there is a multitude of support for new serverless opportunities you can tap into with SignalR, like the new SignalR bindings for Azure Functions. With other advanced capabilities in SignalR like non-JSON payload support and streaming, it’s never been a better time to do real-time than right now. In this demo-heavy, interactive session you’ll be up and running with SignalR in new and more exciting ways.
