### ISSUE TITLE
April 14, 2020 Meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#24]
Meeting Date: April 14, 2020  
Speaker: 
Sponsor: Issuetrak @drew-carpenter

**Comment by drew-carpenter** [comment]
Issuetrak will sponsor for April

**Comment by lvanlowe** [comment]
I will be able to speak

**Comment by 1kevgriff** [comment]
Thanks @lvanlowe!!!

**Comment by Blue-speed** [comment]
@lvanlowe can you provide a bio and short synopses of your talk? Thanks.

**Comment by 1kevgriff** [comment]
Shot an email to @lvanlowe - this meeting with be virtual.

**Comment by 1kevgriff** [comment]
@lvanlowe prefers not to do virtual meetings, so we'll save him to a physical meeting whenever we're allowed to have them again!

**Comment by mgroves** [comment]
I'd be happy to. Some of the sessions I have prepared: crosscuttingconcerns.com/speaking

**Comment by 1kevgriff** [comment]
@mgroves I'll poll the group and see what they want by EOW.

**Comment by 1kevgriff** [comment]
@mgroves How about 'Autonomous Microservices'?

**Comment by mgroves** [comment]
Works for me @1kevgriff - what else do you need from me?

**Comment by 1kevgriff** [comment]
@mgroves I'll email you a panelist link for Zoom webinar.

**Comment by 1kevgriff** [comment]
@mgroves @drew-carpenter you both should have got panelist emails for the meeting.  We're using zoom webinar to help keep a handle on chatter

**Comment by mgroves** [comment]
Is there a URL I should use to promote/tweet the upcoming meetup? @1kevgriff

**Comment by 1kevgriff** [comment]
https://www.meetup.com/Hampton-Roads-NET-Users-Group/events/269729578/
