### ISSUE TITLE
September 11th, 2018 Meeting - Dylan Sheffer

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#3]
Date: September 11th, 2018
Speaker: Dylan Sheffer @dylansheffer 
Sponsors: Issuetrak

**Comment by 1kevgriff** [comment]
@dylansheffer SOLD

**Comment by dylansheffer** [comment]
# Accessibility isn't inaccessible!

## Bio

### Name:
 Dylan Sheffer

### About: 
Dylan Sheffer is a web developer with a passion for accessibility and user-centered design working for Swift Kick. Outside of code, he enjoys playing Stardew Valley, creating cocktails, and drinking tea.

## Abstract

Accessible web development, on the surface, appears to be intimidating and frustrating. However, by learning the essentials on how assistive technology works, how to leverage built-in HTML semantics, and by simplifying overly complicated vocabulary, you will be well on your way to create an inclusive user experience that delights every user.
