### ISSUE TITLE
October 13th, 2020 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#30]
Meeting Date: October 13th, 2020
Speaker: Chad Green (@chadgreen)

**Comment by chadgreen** [comment]
How about I give me talk about Cosmos Change Feed?  here are the details:

Ch-ch-ch-changes: Tracing Changes in Azure Cosmos DB

David Bowie might not be able to trace how time changes him, but with the Azure Cosmos DB change feed allows us to trace the changes to your data within your Cosmos database.  The Azure Cosmos DB change feed listens to an Azure Cosmos container for any changes and then outputs the sorted lists of documents that were changed.  In this session, you learn what the change feed is, how it works, and how you can use it to build more robust applications.

Chad Green
Chad Green is a manager, software development, architect, community leader, Microsoft MVP, and most importantly a father and husband.  Chad works as the Director of Software Development fort ScholarRx developing an affordable, lifelong digital-learning platform for medical students and physicians everywhere.  Over his career spanning three decades, Chad has managed groups from 3 to 63 people, worked on projects in a wide range of markets including education, healthcare, military, government, workforce management, financial services, chemical research, and electronic commerce.  Being a big believer in giving back and wanting to ensure that there are cool events for others, Chad founded and chairs the annual Code PaLOUsa conference, organizers the Louisville .NET Meetup user group and the Monthly Tech Leader Coffee and Discussion and has helped other groups like the Louisville Tech Ladies and events like Cincy Deliver.

**Comment by 1kevgriff** [comment]
SOLD
