### ISSUE TITLE
February 9, 2021 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#34]
Meeting Date: February 9, 2021  
Speaker: Joe Guadagno (@jguadagno)

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by jguadagno** [comment]
I'm available.  Sessions can be found at https://www.josephguadagno.net/presentations.

**Comment by 1kevgriff** [comment]
@jguadagno Let's do Feb.  What topics could you have ready for that?

**Comment by jguadagno** [comment]
- [A lap around Azure](https://www.josephguadagno.net/presentations/a-lap-around-microsoft-azure)
- [Application Architecture Patterns](https://www.josephguadagno.net/presentations/application-architecture-patterns)
- [Debugging Tips and Tricks in Visual Studio](https://www.josephguadagno.net/presentations/debugging-tips-and-tricks-with-visual-studio) - Doing the for Las Vegas UG next week
- [.NET 5 - What is it?](https://www.josephguadagno.net/presentations/dotnet5-what-is-it)
- [Look into your App with Application Insights](https://www.josephguadagno.net/presentations/look-into-your-application-with-application-insights)
- [Migrate It!](https://www.josephguadagno.net/presentations/migrate-it) Could be a little longer than an hour
- [Presentation Preparedness](https://www.josephguadagno.net/presentations/presentation-preparedness)
- [Write Once, Run Anywhere](https://www.josephguadagno.net/presentations/build-a-native-mobile-application-using-react-native-and-javascript) React Native talk

Bio can be found at [About Me](https://www.josephguadagno.net/about-joseph-guadagno/)

**Comment by 1kevgriff** [comment]
@jguadagno Let's do "Application Architecture Patterns"
