### ISSUE TITLE
August 10, 2021 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#41]
Meeting Date: August 10, 2021  
Speaker: Chris Woodruff (@cwoodruff)

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by 1kevgriff** [comment]
Claimed by Chris Woodruff (@cwoodruff)

**Comment by cwoodruff** [comment]
Bio
Chris Woodruff, AKA Woody, is the Team Leader of Developer Relations at Quicken Loans, the nation’s largest mortgage lender based in Detroit, Michigan. Woody has over 25 years of experience when he started his career before the first .COM boom. He has spoken at many events worldwide, covering software development and architecture topics such as database development, APIs, and web development. He is a proven mentor who enjoys helping, educating, and supporting other developers to gain knowledge through speaking, writing, and online content. When not working or spending time with his family, you can find Woody traveling down the Bourbon Trail to find new bottles to share with friends. You can read more about Woody on his blog at https://chriswoodruff.com and follow him on Twitter at @cwoodruff

Pic
http://www.chriswoodruff.com/wp-content/uploads/2018/08/WoodyNewMug400x400.png

Title
What’s new in Entity Framework Core 5?

Abstract
Entity Framework (EF) Core is the lightweight, extensible, and cross-platform version of Entity Framework, the popular Object/Relational Mapping (O/RM) framework for .NET. This talk will give an in-depth look at the new features for .NET 5 and past features still valuable. We will look at the latest release, how to install it, and show sample projects covering the following topics:

- Many-to-many (Finally!!!)
- Split queries
- Simple logging and improved diagnostics
- Filtered include
- Flexible entity mapping
- Shared-type entity types and property bags
- Required 1:1 dependents
- DbContextFactory
- Plus, many more!!!

**Comment by 1kevgriff** [comment]
I'm getting topic feedback from the group right now!  We'll decide by the end of the week.

**Comment by 1kevgriff** [comment]
@cwoodruff Let's go ahead and do the EF talk - looking forward to it!

@drewgle update on the meetup?

**Comment by drewgle** [comment]
Meeting has been published on meetup https://www.meetup.com/Hampton-Roads-NET-Users-Group/events/279336661
