### ISSUE TITLE
October 12, 2021 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#43]
Meeting Date: October 12, 2021  
Speaker: [ TODO ]  

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by 1kevgriff** [comment]
@drewgle abstract/bio pending

**Comment by 1kevgriff** [comment]
@drewgle Abstract/bio updated above

**Comment by 1kevgriff** [comment]
@drewgle moving Taylor to November - he had a conflict come up
