### ISSUE TITLE
January 11, 2022 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#46]
Meeting Date: January 11, 2022  
Speaker: Chris Gardner (@freestylecoder)

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by freestylecoder** [comment]
I should be able to do your January meeting. Just give me an idea of which type of talk you may like (beginner, intermediate, etc)

**Comment by 1kevgriff** [comment]
Thanks @freestylecoder!  Beginner talks usually work well for online mediums.  Whatcha got?

**Comment by freestylecoder** [comment]
You can look at all the talks I have at https://sessionize.com/cgardner/  The only one I don't do virtually is the "Macroservices" talk. "Understand How Your CPU Thinks" and "Creating NuGet Packages" seem to go well with more beginner audiences.
