### ISSUE TITLE
December 11th, 2018 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#5]
Date: December 11th, 2018
Speaker: [ TODO ]
Sponsor:  [ TODO ]

**Comment by 1kevgriff** [comment]
Woo woo!

**Comment by BretFisher** [comment]
## Event Title

Hands-on Labs: Modernizing Windows Applications with Docker!

## Description

HRNUG and Docker Hampton Roads meetups are joining forces for a night of hands-on workshops. Bring your laptop and let’s #LearnDocker.

Our main focus will be a lab where you'll learn to Dockerize traditional .NET / Windows applications! We will also have a number of other labs available on a variety of Docker topics and for different skill levels, including for beginners.

Moving an application to Docker doesn't mean you have to re-write your whole application. In this hands-on technical lab, you'll containerize an older, monolithic .NET application without changing any code. And you'll see the benefit of running it on Docker. Then in a few simple steps, you'll build additional services in separate containers, breaking features out of the monolith into separate containers, without rewriting the app.

If you are an advanced Docker user who would like to help people work through the labs, reach out to Kevin, Drew or Bret! 

Food and drinks will be provided! Let everyone know you’re coming by using #LearnDocker. 

## Agenda 

5:45pm - 6:15pm	Doors Open, Food and Socializing 
6:15pm - 5:45pm	Welcome Message & Intro Slides
6:45pm - 8:15pm	Hands-on Labs
8:15pm		        Wrap up, closing remarks

**Comment by 1kevgriff** [comment]
I'm going to try to get Microsoft sponsored Subway or Dominoes.

**Comment by BretFisher** [comment]
@1kevgriff do those times look good?

**Comment by BretFisher** [comment]
my event is posted https://www.meetup.com/Docker-Hampton-Roads/events/256250446/
