### ISSUE TITLE
October 11, 2022 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#55]
Meeting Date: October 11, 2022
Speaker: Adam Lenda

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by 1kevgriff** [comment]
Speaker: Adam Lenda
Title: Lessons from 20 years of Software Engineering

Abstract
“Lessons from 20 years of Software Engineering” is a presentation based on the hard lessons Adam has learned through his own mistakes. It came to be as part of an attempt to codify the soft skills that are most important to convey when mentoring software engineers. The presentation will include stories of how he messed up, and the changes that helped keep those mistakes from repeating. Adam hopes that these anecdotes can be useful to others, and invites the attendees to discuss, challenge, and dissect his conclusions.

Bio
Adam Lenda began a mostly self-taught path to writing software in 1997. While enthusiastic about the scientific aspects of computer science, he has spent his professional life almost exclusively building business web applications. Throughout Adam’s career, he has sought to pass on the things he found useful. As there seems to be more than enough technical talks, his presentations, such as “Managing Technical Debt,” generally focus on the soft skills that build engineers and facilitate difficult projects.
Adam currently works as API Architect for Relativity, an e-discovery platform.

**Comment by 1kevgriff** [comment]
@drewgle we got a speaker!
