### ISSUE TITLE
February 14, 2023 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#59]
Meeting Date: February 14, 2023  
Speaker: Josh Carlisle @joshdcar 

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by joshdcar** [comment]
Hi Kevin,

I have some availability for Feb 14 - let me know if you're interested in the following:

**Title:** Taking Care of Business – Building Microservices with Dapr and .Net
**Description:** The benefits of distributed applications architectures based on microservices are well established but so are the complexity and challenges that come along with them. Before you write a single line of code that addresses the business needs of your application you have to address numerous critical crossing-cutting concerns. Skip or come up short in any of these areas and you add considerable risk to the success of your application. This is where Dapr, the Distributed Application Runtime, comes in. Dapr provides a set of building blocks that take care of many common use cases for distributed applications and microservices. Join me in this talk where you'll learn about the benefits of Dapr, how to get started using dapr with .Net, and some of the best ways you can deploy Dapr-powered applications to Azure.

**Bio:** 
Josh Carlisle is a Principal Engineer on the Zscaler Posture Control (ZPC) team where he is a founding architect for the ZPC platform and a leader on the platform engineering team. He is an industry veteran with over 25 years of experience architecting and developing enterprise and cloud native applications. He has been contributing to the technology community for most of his career and can be found speaking at user groups, meetups, and conferences around the world. Josh has been recognized by Microsoft for his community contributions and is currently a Microsoft MVP in Azure.


Ref: https://sessionize.com/s/joshcarlisle/taking-care-of-business-building-microservices-wit/62360

**Comment by 1kevgriff** [comment]
@joshdcar SOLD

**Comment by 1kevgriff** [comment]
@drewgle Check it out!  @joshdcar is also going to drive up and speak in person
