### ISSUE TITLE
March 14, 2023 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#60]
Meeting Date:  March 14, 2023  
Speaker: Dan Moore (@mooreds)

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by mooreds** [comment]
I'd be happy to talk about 

* Using oauth to protect APIs
* JWTs 
* WebAuthn

Let me know which would be of most interest to your members. 

I'd need to zoom in.

**Comment by AdoraNwodo** [comment]
I'd be happy to talk about IaC using Azure Bicep

**Comment by 1kevgriff** [comment]
> I'd be happy to talk about IaC using Azure Bicep

@AdoraNwodo thank for your interest!  Looks like @mooreds requested first.  Could you please look at one of the other available months: https://github.com/HRNUG/Organization/issues?q=is%3Aopen+is%3Aissue+label%3A%22NEED+SPEAKER%22

Thanks!

**Comment by mooreds** [comment]
@1kevgriff wanted to confirm I'm still on for Mar 14.

**Comment by drewgle** [comment]
@mooreds you are still on. Lets do the `Using oauth to protect APIs` talk. Can you provide us a short bio and talk description?

**Comment by 1kevgriff** [comment]
@mooreds After we get our meetup setup, I'll email you a Streamyard link for next Tuesday.

**Comment by mooreds** [comment]
Perfect, @drewgle @1kevgriff .

Here's my bio and talk description.

OAuth is a well known standard and is useful for delegating authentication and authorization decisions to a central identity provider. As a developer, you’ve given a token when a grant completes.

But what happens then? This talk will discuss client and server side code and logic needed when calling an API after you have a token. This will include how to store a token in the API client and what your API code should examine when presented with a token.

Bio: 

Dan Moore is head of developer relations for FusionAuth, where he helps educate developers on authentication and authorization best practices. A former CTO, engineering manager and longtime developer, he's been writing software for (checks watch) over 20 years.

**Comment by 1kevgriff** [comment]
@mooreds I'll email you a streamyard link and calendar item later today!

Thanks!
