### ISSUE TITLE
April 11, 2023 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#61]
Meeting Date: April 11, 2023  
Speaker: Adora Nwodo (@AdoraNwodo)

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by AdoraNwodo** [comment]
I'd be happy to talk about IaC using Azure Bicep.

You can find my bio [here](https://docs.google.com/document/d/1PIUDORkUT5vBCpeLahbPxrAQRSixWtoffl1l7K16KDI/edit?usp=sharing)

**Comment by 1kevgriff** [comment]
@AdoraNwodo you're in!

**Comment by 1kevgriff** [comment]
@AdoraNwodo Can you provide us with an abstract for your talk?

**Comment by AdoraNwodo** [comment]
In recent times, we have seen infrastructure automation play a very important role in building and shipping world class applications fast. We have seen how tools like Docker, Ansible, Puppet & Terraform can be used to automate infrastructure deployments.

In this session, I would talk about the concept of Infrastructure as code and how I'm able to treat my infrastructure deployment code the same way I treat my source code (testing, version control and graceful rollbacks).

Are you a Software Engineer looking to create infrastructure for your applications without prior DevOps knowledge or are you a DevOps Engineer looking to try something new and straightforward when it comes to infrastructure automation? If you are, then this session is for you!

I would talk about Azure Bicep: A DSL that allows me provision infrastructure for all Azure resources. This means that for me to automate my infrastructure, I do not need to write so much JSON using ARM templates. I would also share my first experience with Azure Bicep, how it works and how I use my transferrable programming knowledge for infrastructure deployments to Azure easily.

**Comment by AdoraNwodo** [comment]
Here it is :)
