### ISSUE TITLE
May 9, 2023 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#62]
Meeting Date: May 9, 2023  
Speaker: @RVAProgrammer Tom Becker

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by RVAProgrammer** [comment]
Kevin, if you still need a speaker for this event I would be interested in doing an introduction to Blazor Presentation.  If you are interested I can pop in a bio and full description.

**Comment by 1kevgriff** [comment]
@RVAProgrammer absolute - drop a bio/abstract and please send me an email `kevin` at `consultwithgriff` dot com

Thanks!

**Comment by RVAProgrammer** [comment]
### Introduction to Blazor
What is Blazor?  Is this another flash in the pan front end technology?  Is this the next Silverlight or LightSwitch?  Tonight we will discuss the pros and cons of Blazor and build an simple application together using Blazor WASM (web assembly) to show the power and the ease of thinking in one language all day long.


### Tom Becker Bio
Tom Becker is a Microsoft Architect at CapTech Ventures and is based in Richmond, VA.  He is a Navy brat and spent a good chunk of his years right here in Hampton Roads.  After high school Tom studied computer science and math at Randolph-Macon college (Go Jackets!) and has worked in and around Richmond for the past 18 years trying to perfect the craft.
